name: unit-test

on:
  push:
    branches: [ main ]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    env:
      MULTITOKEN_METADATA_URI: ${{ secrets.MULTITOKEN_METADATA_URI }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up node 
        uses: actions/setup-node@v1
        with:
            node-version: 18.15.0

      - name: Install truffle
        run: npm install -g truffle

      - name: Install dependencies
        run: npm install  
      
      - name: Start Ganache
        run: docker run -d -p 7545:8545 trufflesuite/ganache-cli

      - name: Compile contracts
        run: truffle compile

      - name: Run unit tests 
        run: truffle test