name: unit-test

on:
  push:
    branches: [ main ]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up node 
        uses: actions/setup-node@v1
        with:
            node-version: 18.15.0

      - name: Install truffle
        run: npm install -g truffle
      
      - name: Start Ganache
        uses: trufflesuite/ganache-cli-action@v2
        with:
          version: 'latest'
          port: 7545   

      - name: Compile contracts
        run: truffle compile
            
      - name: Run unit tests 
        run: truffle test